image: golang:1.8

variables:
  GO_PROJECT: gitlab.com/psheets/ddgquery

stages:
  - test

before_script:
  - mkdir -p ${GOPATH}/src/${GO_PROJECT}
  - mkdir -p ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}
  - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}
  - go get github.com/PuerkitoBio/goquery/


test-my-project:
  stage: test
  script:
    - go test -v -cover
