image: golang:1.8

stages:
  - test

before_script:
  - ln -s /builds/psheets/ddgquery /go/src/gitlab.com/psheets/ddgquery
  - go get github.com/PuerkitoBio/goquery/


test-my-project:
  stage: test
  script:
    - go test -v -cover
